# Generated by Django 3.2 on 2022-07-17 14:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20220708_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 17, 14, 40, 22, 838612, tzinfo=utc), verbose_name='زمان پیام'),
        ),
    ]
