# Generated by Django 3.2 on 2022-07-20 05:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20220717_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 20, 5, 15, 19, 739121, tzinfo=utc), verbose_name='زمان پیام'),
        ),
    ]
